### ISSUE TITLE
(cozy-ui) toggles or other notation for pruning

### ISSUE THREAD

**Issue by gregsgit** [draperlaboratory/cozy#7]
There should be a way to see what pruning filters are in effect for current view.
One idea is to treat checkboxes in "prune" menu as stateful checkboxes. E.g. when "prune/identical memory" toggle box is clicked, to then show it checked when pull down prune menu again. To turn off that pruning, re-click the toggle box. Simple toggle checkboxes should work except for regexp matching against stdout.  For regexp matching against stdout, I don't see why it should be a checkbox. Currently it defaults to ".*" which means nothing is filtered out. I suggest simply making it a persistent field that can always be changed. E.g. from ".*" to "bad input:.*" or to "bad.* | invalid.*" etc.

**Comment by gleachkr** [comment]
Closed by d61ecee
