### ISSUE TITLE
(cozy-ui) single json for pairs of binaries

### ISSUE THREAD

**Issue by gregsgit** [draperlaboratory/cozy#9]
Currently, pairs of json files output by cozy analysis are essentially tide together; that is, visualization of json files not created together may produce nonsense.
Therefore, a single json file should contain analysis information for a pair of binaries.
Also, consistent with issue #8, information about the binaries analyzed (and options sent to cozy, etc.) should also be stored in json files.

**Comment by gleachkr** [comment]
The new data format is 
```
{
  "pre" : {
       "name" : PREPATCH BINARY NAME,
       "data" : OLDFORMAT
   },
   "post" {
       "name" : POSTPATCH BINARY NAME,
       "data" : OLDFORMAT
   }
}
```
So to migrate old traces that you don't want to regenerate, you can use the following `jq` command:
```
jq -n '{pre:{name:"prepatch",data:input},post:{name:"postpatch",data:input}}' oldpre.json oldpost.json > combined.json
```
